# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dylan Scott Low Y.J.
tagline:          "Cognitive Science of Language"
# The description is used in the meta description tag (_includes/head.html).
# If you want to use it in the sidebar, uncomment its code under the tagline
# in _includes/sidebar.html
description:      "Dylan's academic website."
url:              https://dylanscottlow.github.io
baseurl:          

author:
  name:           "Dylan Scott Low Y.J."
  url:            https://dylanscottlow.github.io

paginate:         3
paginate_path: "/blog/:num/"
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

github: [metadata]

#Custom blog post excerpt separator as recommended by ChatGPT
excerpt_separator: "<!-- more -->"
